### ISSUE TITLE
Flask-admin isn't Content Security Policy-friendly

### ISSUE THREAD

**Issue by toolness** [pallets-eco/flask-admin#1135]
My current project uses [Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/); one of the default behaviors for CSP is to prevent the execution of inline scripts, which improves resilience in the face of XSS attacks and the like.

However, it seems that there a handful of inline `<script>` tags in flask-admin views, like the following one which appears on my model list view:

``` html
<script language="javascript">
        (function($) {
            $('[data-role=tooltip]').tooltip({
                html: true,
                placement: 'bottom'
            });

        })(jQuery);
    </script>
```

Similar to https://github.com/mgood/flask-debugtoolbar/issues/88, some of these can be worked around by a [hash-source](https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/) CSP directive, but it'd be really awesome if flask-admin was compatible with the most helpful CSP defaults out-of-the-box!

**Comment by mrjoes** [comment]
Pull requests are always welcome!

**Comment by jxltom** [comment]
Why this is closed?

**Comment by petrus-jvrensburg** [comment]
@jxltom let me re-open it. Are you working on a fix? A pull-request would be great!

**Comment by petrus-jvrensburg** [comment]
@jxltom let me re-open it. Are you working on a fix? A pull-request would be great!

**Comment by jxltom** [comment]
Probably it will be better to keep this open since it is not solved and then someone may fix this. :smile:

I can't gurantee the PR but I will try to do that since CSP is important for securities.

**Comment by nk9** [comment]
A number of the portions of code which need to be modified are in bootstrap3 and 4. What is the flask_admin policy on modifying vendor code?

**Comment by nk9** [comment]
I can't guarantee I'll fix this, but I have done some amount of work on it so I can use it on my site. I am working toward a PR, we'll see. But it would be very helpful to get an answer about modifying upstream code which flask-admin has forked in its repo. @petrus-jvrensburg @mrjoes is there a policy on this? If it's not possible to change those, then there's little point in me doing the work for a PR.

**Comment by petrus-jvrensburg** [comment]
Nope. Modifying the vendor code in this repo isn't a good idea. It would make it too difficult to update dependencies later.

I would suggest to either fork the project to maintain your own versions of the modified vendor code, or to implement some alternative template mode that doesn't rely on the problematic vendor code at all.

**Comment by nk9** [comment]
Yeah, I've had to make my own fork. While I understand the reasons, that's unfortunate—it means Flask-Admin will be [waiting for bootstrap](https://github.com/twbs/bootstrap/issues/25394#issuecomment-443987750) to support CSPs. Still, there's non-vendor code to change, so this issue should remain open.

**Comment by dfeinzeig** [comment]
anyone already have hashes handy to work around this?

**Comment by errorfourten** [comment]
> 
> 
> anyone already have hashes handy to work around this?

For "return modelActions.execute('delete');", you can use 'sha256-ftmTNsdfRKq6ZNyHL+p7dI9xRqueDTpseN1IaUUgQW4='

For "return faHelpers.safeConfirm('Are you sure you want to delete this record?');", you can use 'sha256-gikCNhEl+fhjSb8779qEr3zNPPm8nyTyg8MPyBYs+Tw=\'

These are the only scripts I have found that needed hashing. Just leaving them here in case any future person needs them!

**Comment by samuelhwilliams** [comment]
Thanks for reporting this issue. As there are a few issues open on the topic of CSP, I'm go to close this one in favour of https://github.com/pallets-eco/flask-admin/issues/2344, so that we can keep conversation in one place.
