### ISSUE TITLE
MongoEngine: optional EmbeddedDocumentFiled

### ISSUE THREAD

**Issue by shvechikov** [pallets-eco/flask-admin#1202]
I have found how to manage lists of embedded documents, so I can add/remove subforms (it represents one-to-many relation between document and subdocument).
But what about **optional** EmbeddedDocumentFiled? I want to be able to remove embedded form if the field is optional (like list items but like it is optional one-to-one relation).

Let me show an example:
![2016-02-15 10 30 23](https://cloud.githubusercontent.com/assets/12324/13042188/4c835a78-d3cf-11e5-99d3-d515d3f29d4a.png)

As you can see I can add/remove buttons but can't remove dialog field itself despite the fact that it is not required field. It should work almost the same way as it does with buttons.

I can try to make a pull request if you approve this change.

**Comment by ufo911** [comment]
Have you made PR ?

**Comment by samuelhwilliams** [comment]
I am closing this issue as we've removed support for flask-mongoengine, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
