### ISSUE TITLE
Error with ListField(ReferenceField) and MongoEngine after updating with add_to_set__

### ISSUE THREAD

**Issue by fmatray** [pallets-eco/flask-admin#1298]
A small issue when using flask-admin and mongoengine.

Example of error:
'''
class User(UserMixin, db.Document):
    email = db.StringField(max_length=80)
class Team(db.Document):
    members=db.ListField(db.ListField(db.ReferenceField(User), default=[]))

def teaminvite(team_id=None):
...
  t=Team.objects.get(id=team_id)
  u=User(email=form.email.data).save()
  t.update(add_to_set__members=u)
..
'''
Editing team with flask-admin works fine before the teaminvite.
But once a user is added using _add_to_set__members_ an error appeared in admin.

```
TypeError: getattr(): attribute name must be string
...
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_mongoengine/wtf/fields.py", line 117, in _is_selected
return item in self.data
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mongoengine/base/document.py", line 240, in __contains__
val = getattr(self, name)
```

This is a correction (perhaps not the best) :
'''
class QuerySetSelectMultipleField(QuerySetSelectField):
...
    def _is_selected(self, item):
        if not self.data:
          return False
        if self.data is list:
          return item in self.data
        else:
          return item in [self.data]
'''

**Comment by ljluestc** [comment]
```

from flask import Flask
from flask_mongoengine import MongoEngine
from flask_admin import Admin
from flask_admin.contrib.mongoengine import ModelView
from flask_admin.form import rules
from mongoengine import ListField, ReferenceField, StringField

app = Flask(__name__)
app.config['MONGODB_SETTINGS'] = {
    'db': 'your_db_name',
    'host': 'your_mongodb_uri'
}
db = MongoEngine(app)

# Define User model
class User(db.Document):
    email = db.StringField(max_length=80)

# Define Team model
class Team(db.Document):
    members = db.ListField(db.ReferenceField(User), default=[])

# Create the database tables (if not created already)
db.create_all()

# Create Flask-Admin instance
admin = Admin(app, name='Flask Admin', template_mode='bootstrap3')

# Register ModelViews for User and Team
class UserView(ModelView):
    column_list = ('email',)
    form_create_rules = ('email',)

class TeamView(ModelView):
    column_list = ('members',)  # Customize columns as needed

    # Override form rules to use Select2Field
    form_create_rules = ('members', rules.Field('members'))

admin.add_view(UserView(User))
admin.add_view(TeamView(Team))

if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by samuelhwilliams** [comment]
I am closing this issue as we've removed support for flask-mongoengine, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
