### ISSUE TITLE
Flask Admin doesn't work with host_matching = True

### ISSUE THREAD

**Issue by blark** [pallets-eco/flask-admin#1395]
I Googled to see if there was some workaround for this but couldn't find any mention of host matching in the documentation for Flask Admin. After looking at the source briefly, I'm not sure how to proceed.

I have an application that requires that I set `app.url_map.host_matching = True` so I can route different domain requests appropriately. When I do this the basic Flask Admin example [here](https://flask-admin.readthedocs.io/en/latest/introduction/#getting-started) stops working. I'm assuming that this is because the admin URL is now unmatched. 

**Edit**

I've been looking at the routes that are created when I run `admin = Admin(app, name='microblog', template_mode='bootstrap3')` they look like this:

```
In [3]: app.url_map
Out[3]: 
Map([<Rule '/admin/' (OPTIONS, HEAD, GET) -> admin.index>,
 <Rule '<host>.bar.io|/static/<filename>' (OPTIONS, HEAD, GET) -> secure_file.static>,
 <Rule '/admin/static/<filename>' (OPTIONS, HEAD, GET) -> admin.static>,
 <Rule '<host>.derp.com|/foo' (OPTIONS, HEAD, GET) -> secure_file.foo>,
 <Rule '<host>.foo.com|/' (OPTIONS, HEAD, GET) -> bonus.index>,
 <Rule '<host>.bar.io|/' (OPTIONS, HEAD, GET) -> secure_file.index>])
```

As you can see there is no `<host>|` rule to match so the URLs never get matched and don't route. Perhaps when instantiating `Admin` if `app.url_map.host_matching = True` the user should provide a host paramater to be added to the route?

**Comment by blark** [comment]
After some further hacking around in [base.py](https://github.com/flask-admin/flask-admin/blob/d7ee730adfc22d878d449fcfcdbdce9bb9ab7bfd/flask_admin/base.py#L273) I confirmed that adding a `host='foo.bar'` parameter to the `add_url_rule` function indeed makes the route work. It's not so easy to use a pattern like `<host>` though because none of the downstream functions are expecting that so things break. 

In addition flask itself is broken, when it makes static routes it also doesn't take into account the host parameter as per [this issue which has been open for 15 months](https://github.com/pallets/flask/issues/1559). So instead you have to manually register the static file route like so: 
```
app.add_url_rule('/static' + '/<path:filename>', endpoint='secure_file.static',
                 view_func=app.send_static_file, host=host_pattern)
```

Hope all this helps...

**Comment by bmjjr** [comment]
@blark I found similar, adding host='foo.bar' makes the route work, except all the flask-admin static files are not found. Did you find some way to overcome this?

**Comment by samuelhwilliams** [comment]
Is there any prioritisation/scope for fixing this?

**Comment by samuelhwilliams** [comment]
I have provisionally put up a patch that should add basic host matching support (ie a single explicit host; no Werkzeug URL variables): https://github.com/pallets-eco/flask-admin/compare/master...samuelhwilliams:flask-admin:add-host-support

Will try and flag this on pallets-eco to get some discussion and think about a PR.
