### ISSUE TITLE
Password hash too large for database.

### ISSUE THREAD

**Issue by spitfiredd** [pallets-eco/flask-admin#1450]
In your User model you define 

`password = db.Column(db.String(64))`

It kicks back an error on the database (using Postgres 9.6) because the hash that the registration generates is larger than varchar(64).  

I noticed other models have `db.String(255)` is 255 large enough? Would leaving it blank and up to the database cause issues for certain databases?

**Comment by xqliu** [comment]
I think length of password depends on the hash algorithm of your own choice.

Generally 255 character is enough for most algorithms.

**Comment by adamrt** [comment]
@spitfiredd If your question was answered can you close this ticket, please?
