### ISSUE TITLE
auth-mongoengine does not run throws ValidationError 

### ISSUE THREAD

**Issue by bedarkarpriyanka** [pallets-eco/flask-admin#1453]
mongoengine.errors.ValidationError 
ValidationError: u'22' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string

is it because, flask_login is trying to load_user(user_id) where user_id is not a valid ObjectId?

**Comment by ljluestc** [comment]
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user

app = Flask(__name__)
app.config['MONGODB_SETTINGS'] = {
    'db': 'your_database_name',
    'host': 'your_mongodb_uri'
}
db = MongoEngine(app)
login_manager = LoginManager(app)

# Define your User model, which should inherit from UserMixin
class User(db.Document, UserMixin):
    username = db.StringField()
    password = db.StringField()

# Flask-Login's user loader function
@login_manager.user_loader
def load_user(user_id):
    try:
        return User.objects.get(id=user_id)
    except User.DoesNotExist:
        return None

# Sample route for logging in
@app.route('/login/<user_id>')
def login(user_id):
    # Ensure that 'user_id' is a valid ObjectId
    if len(user_id) != 24:
        return "Invalid user_id", 400

    # Load the user and log them in
    user = load_user(user_id)
    if user:
        login_user(user)
        return "Logged in as " + user.username
    else:
        return "User not found", 404

# Sample route for a protected resource
@app.route('/protected')
@login_required
def protected():
    return "This is a protected resource"

# Sample route for logging out
@app.route('/logout')
@login_required
def logout():
    logout_user()
    return "Logged out"

if __name__ == '__main__':
    app.run()

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
