### ISSUE TITLE
Any plans to support bootstrap 4? 

### ISSUE THREAD

**Issue by vincentwhales** [pallets-eco/flask-admin#1486]

**Comment by renweibo** [comment]
+1

**Comment by TimotheeJeannin** [comment]
This would be nice !

**Comment by SBillion** [comment]
:+1:

**Comment by jxltom** [comment]
Beside, bootswatch already have themes for Bootstrap v4. It sounds very good to update bootswatch along with bootstrap v4.

**Comment by vincentwhales** [comment]
Any takers?

**Comment by HonzsSedlomn** [comment]
I'm working on it! ;)

**Comment by shiflonium** [comment]
watch +1

**Comment by erik921** [comment]
Looking forward to this!

**Comment by soxepo** [comment]
Any news RG Bootstrap 4 support?

**Comment by sn1p3r46** [comment]
Follow.

**Comment by niap0r** [comment]
Just to be sure, can I use the version from github and use BS4? It seems like the version from pypi has only BS3 support enabled, but looking at those commits I was hoping for BS4 support.
