### ISSUE TITLE
Jade templates stopped to work after updating to 1.5.0

### ISSUE THREAD

**Issue by devunion** [pallets-eco/flask-admin#1518]
Hi,
I've updated today Flask-Admin version from 1.4.2 to 1.5.0. My jade templates stopped to work. All was OK on the previous version. Updated to latest pyjade. No success. 

Even empty templates with one line produce this problem:
`{% extends 'admin/model/edit.html' %}`

Screenshot: http://imgur.com/9fZHwpC

Jade templates still work normally on the main site pages outside of Flask-Admin.

Any ideas how to troubleshoot this?

**Comment by ljluestc** [comment]
```

from flask import Flask
from flask_jsglue import JSGlue
from flask_pymongo import PyMongo
from flask_bootstrap import Bootstrap

app = Flask(__name__)
jsglue = JSGlue(app)
app.config['BOOTSTRAP_SERVE_LOCAL'] = True
app.config['SECRET_KEY'] = 'Thisisasecret'
app.config['MONGO_DBNAME'] = 'example'
Bootstrap(app)
PyMongo(app)
```
