### ISSUE TITLE
"column_editable_list" need update

### ISSUE THREAD

**Issue by huang-zp** [pallets-eco/flask-admin#1529]
If it is a date, it is up to 2015， should be 2017

**Comment by gordol** [comment]
Better yet...

Why is this using a different input type than the rest of flask-admin?

It uses a datepicker elsewhere, but in the x-editable view we are using individual selectors for each unit of the datetime.

![](https://lh5.googleusercontent.com/hQo6dXaRACUfVpZWsyi9vTkY8ONr2tnfoIO304yHwcXdMwqtFPpIQYeT1YIIEEzelGodnJ_UknDm-pc=w2560-h1318)

vs

![](https://lh6.googleusercontent.com/rDFp0JpMGrLInivAAGDIXuRciaHXdMpFWm0RVMD1ypd0iSV4ghPSrUEDnZ6g03tzTL57UPUkCQNfvYU=w2560-h1318)

If we switched it to use the datepicker, not only would it fix this issue of having the hard-coded 2015 year, but it would also make the admin panel more consistent.

**Comment by sn1p3r46** [comment]
865668f extends the range, but, it would be nice to have a smarter solution like automatic range, not hard-coded silutions
