### ISSUE TITLE
Highest year is 2015 when editing datetime fields

### ISSUE THREAD

**Issue by JasonCrowe** [pallets-eco/flask-admin#1543]
Title says it all...

I have a datetime field in my database, when I go to edit the field in flask-admin, the item has dropdowns for the year by 2015 is the highest year I can choose.

**Comment by mrjoes** [comment]
Can you make a short gist illustrating the issue? Flask-Admin uses this to as a date/time picker: https://github.com/flask-admin/flask-admin/tree/master/flask_admin/static/vendor/bootstrap-daterangepicker and not passing an upper limits to the initialization function: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/static/admin/js/form.js#L344

**Comment by JasonCrowe** [comment]
That's the datetime picker it uses when creating a datetime, but when I edit a datetime object.

![datetime_error](https://user-images.githubusercontent.com/1906730/30829355-2ea96856-a206-11e7-995f-7c401832f489.gif)

**Comment by JasonCrowe** [comment]
The blank box is where I would select the year, but 2015 is the highest option.

**Comment by mrjoes** [comment]
Yep, reproduced. We use x-editable which then uses http://vitalets.github.io/combodate/

Their demo page has 2015 as a maximum year. I'll see if there's an easy way to override it.

**Comment by mrjoes** [comment]
Pushed a fix, see if master version branch works for you.

**Comment by JasonCrowe** [comment]
I updated using the following command:
pip install -U git+https://www.github.com/flask-admin/flask-admin.git

I am a git newbie, so I'm not sure if that was correct or not. You can see in the attached photo, that it didn't fix the issue and it now cuts off the top of the selector.

![datetime_error](https://user-images.githubusercontent.com/1906730/30830459-bdcd4504-a209-11e7-92bc-aae1202d71b8.gif)

**Comment by Feanaur** [comment]
Stumbled upon this one - old bootstrap.min.js that is being pulled by default is causing this issue.

**Comment by jxltom** [comment]
@5fff53b fixed my problem.

**Comment by ysuper** [comment]
[5fff53b](https://github.com/flask-admin/flask-admin/commit/5fff53bc95466317cdff3c68a1b4d748666bf8b7)
fixed datetime picker years bug
![image](https://user-images.githubusercontent.com/25898635/117390577-048c0980-af21-11eb-9ec6-9ac92d7ef4c9.png)
in date picker, 2015 is the highest option too.
![image](https://user-images.githubusercontent.com/25898635/117390597-09e95400-af21-11eb-816f-055d2383176b.png)
this is my model setting
![image](https://user-images.githubusercontent.com/25898635/117390611-0eae0800-af21-11eb-96fc-a3a4569fe88a.png)
how can i fix it?

**Comment by samuelhwilliams** [comment]
I believe this issue is not present in the bootstrap4 theme. If you're using bootstrap2 or bootstrap3 themes, please can you update and try using bootstrap4.

If the problem persists, please raise a new issue :)
