### ISSUE TITLE
Optimizing a big edit view. Where is the code that fills a form on load?

### ISSUE THREAD

**Issue by btseytlin** [pallets-eco/flask-admin#1630]
Hello.
I am using flask admin with mongoengine.

I have a huge `edit_view` with many `AjaxMultipleSelectField` instances, referencing many objects.

By the amount of queries to db with only `_id` and `_cls` specified, its clear flask admin queries all referenced objects one-by-one on page load.

A db query for each of 300+ objects referenced on page, and its too slow.

I would like to optimize the queries that happen on page load. But I have trouble finding the code that makes all these db queries.

I have already switched all ajax lookup fields to a custom optimized field with a custom loader. Ajax lookup got sped up considerably, but `edit_view` still loads very slowly. 

Could you pinpoint which code exactly fills the page with data upon load?

**Comment by ljluestc** [comment]
``` 
from flask_admin.contrib.mongoengine import ModelView
from flask_admin.model.fields import AjaxMultipleSelectField
from flask_admin.contrib.mongoengine.form import CustomModelConverter
from flask_admin.contrib.mongoengine.view import ModelView as CustomModelView

class OptimizedModelConverter(CustomModelConverter):
    def __init__(self, view, additional=None):
        super(OptimizedModelConverter, self).__init__(view, additional)

    def convert_ajax_multiple_select(self, field, model, converter, **kwargs):
        return AjaxMultipleSelectField(field.label, model=field.model, multiple=True, create_field=field.create_field, **kwargs)

class OptimizedModelView(CustomModelView):
    column_type_formatters = CustomModelView.column_type_formatters

    def __init__(self, *args, **kwargs):
        super(OptimizedModelView, self).__init__(*args, **kwargs)

    def get_query(self):
        return self.model.objects.only('id', '_cls')  # Adjust fields as per your model structure

    def get_count_query(self):
        return self.get_query()

    def get_list(self, *args, **kwargs):
        return super(OptimizedModelView, self).get_list(*args, **kwargs)

    def get_one(self, *args, **kwargs):
        return super(OptimizedModelView, self).get_one(*args, **kwargs)

# Usage
admin.add_view(OptimizedModelView(YourModel))
```

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
