### ISSUE TITLE
Mysql Database for flask-admin

### ISSUE THREAD

**Issue by vijaysagi1** [pallets-eco/flask-admin#1638]
Hi,

I have requirement where i need to use mysql as the database where we have other integration data.
Pls suggest what best can be done configure mySQL as the database.

Thanks
vijay

**Comment by jasgrider** [comment]
You should read up on [SQLAlchemy](https://www.sqlalchemy.org/) or any of the other ORMs that flask-admin supports out of the box. An ORM is a layer that simplifies calls to MySQL or any other supported databases. 

Good luck!
