### ISSUE TITLE
Mongoengine EmbeddedDocumentListField not displayed 

### ISSUE THREAD

**Issue by bekab95** [pallets-eco/flask-admin#1644]
```
class Room(Document):
    images = EmbeddedDocumentListField(EmbeddedRoomImages)

class EmbeddedRoomImages(EmbeddedDocument):
    position = IntField()
    image = ImageField(size=(1920, 950), thumbnail_size=(640, 316))
    is_main = BooleanField()
    is_enabled = BooleanField()
    image_big_link = StringField()
    image_thumb_link = StringField()
```

![capture](https://user-images.githubusercontent.com/17232189/40097699-9ed824c0-58e8-11e8-9739-ada797333c16.JPG)

So nothing is to add and why ?

**Comment by david81brs** [comment]
Try reorder the classes. Define EmbededRoomImages first.

**Comment by david81brs** [comment]
How about:
```python

class EmbeddedRoomImages(EmbeddedDocument):
    position = IntField()
    image = ImageField(size=(1920, 950), thumbnail_size=(640, 316))
    is_main = BooleanField()
    is_enabled = BooleanField()
    image_big_link = StringField()
    image_thumb_link = StringField()

class Room(Document):
    images = ListField(EmbeddedDocumentField(EmbeddedRoomImages))

```
Don't forget to import **ListField**.
:bowtie:

**Comment by ufo911** [comment]
@david81brs 

I know that solution but as others suggest EmbeddedDocumentListField is much more efficient and it works without flask admin and i need it to work with flask admin too...

**Comment by david81brs** [comment]
So there isn't support yet. Right?

**Comment by ufo911** [comment]
It seems so

**Comment by ufo911** [comment]
As I see, converter needed for this field for flask-mongoengine also may some checks needed in flask-admin in contrib.mongoengine views.

**Comment by sorXCode** [comment]
Try defining the `__repr__`  method for the embedded class

e.g.
```
class EmbeddedRoomImages(EmbeddedDocument):
    position = IntField()
    image = ImageField(size=(1920, 950), thumbnail_size=(640, 316))
    is_main = BooleanField()
    is_enabled = BooleanField()
    image_big_link = StringField()
    image_thumb_link = StringField()

  def __repr__(self):
    return self.image_thumb_link

  def __str__(self):
    return self.image_thumb_link

```

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
