### ISSUE TITLE
Confusing behavior for mongoengine BooleanField(default=True)

### ISSUE THREAD

**Issue by gordol** [pallets-eco/flask-admin#1704]
1. Define a model, and put a few string fields in it, and link it up with flask admin.
1. Create a document via the admin UI.
1. Add a boolean field to the model, and set the default value to true.
1. Go to admin, and view the model. (note that it says the boolean is toggled on)
1. Save the model to persist the changes to the database.
1. Create a new document via admin.

If you check the actual database, the boolean field will not be present on the preexisting document, but it is stored for the newly created document. It seems maybe there is some dirty checking against admin form inputs and model value state... I can't think of any other reason why the actual value wouldn't be saved to the database... it thinks it was already set since it's on by default, and when you submit the form it doesn't change that state, so it doesn't persist?

I'm not sure whether to blame flask-admin or mongoengine for this, but it's definitely an interesting edge case between the two libraries. I will follow up after I dig into the flask-admin code.

**Comment by gordol** [comment]
I think this may be a mongoengine issue... Will follow up over there.

**Comment by gordol** [comment]
Okay, so [update_model()](https://github.com/flask-admin/flask-admin/blob/7fa26ab227868ff7512bb25c26a30fd7d69184bc/flask_admin/contrib/mongoengine/view.py#L580) is doing [setattr()](https://github.com/flask-admin/flask-admin/blob/7fa26ab227868ff7512bb25c26a30fd7d69184bc/flask_admin/contrib/mongoengine/fields.py#L42) via [populate_obj()](https://github.com/flask-admin/flask-admin/blob/7fa26ab227868ff7512bb25c26a30fd7d69184bc/flask_admin/contrib/mongoengine/fields.py#L37)

If you set a Mongoengine field via attribute and set it to the same value as the "default", it doesn't push the value into the database. You must call .update() on the model for it to actually persist into the database.

Does this mean we need to update the following code?

https://github.com/flask-admin/flask-admin/blob/7fa26ab227868ff7512bb25c26a30fd7d69184bc/flask_admin/contrib/mongoengine/fields.py#L42

Should that be `obj.update({name: candidate})` instead of `setattr(obj, name, candidate)`?

The problem is then there will be many update() calls per Document.

So should we try to work around this in Flask-Admin, or is it better to raise an issue upstream with Mongoengine so that setattr() behaves in a more sane manner?

**Comment by gordol** [comment]
Possibly related: https://github.com/MongoEngine/mongoengine/issues/1756

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
