### ISSUE TITLE
`desc` query string arg incorrectly preserved when setting filters

### ISSUE THREAD

**Issue by ibushong** [pallets-eco/flask-admin#1761]
If you do descending order on a column, the URL will have `?desc=1`. If you then apply a filter, this part of the url becomes `desc=True`, which breaks the `ViewArgs` parsing, resulting in the sorting going back to ascending.

One possible fix (I think..) is to remove the `bool` casting of the `sort_desc` argument to `ViewArgs`

**Comment by ufo911** [comment]
You May Make PR for this

**Comment by ibushong** [comment]
# Steps to reproduce
1. Go to model list view (with data)
2. Sort by descending (e.g. click a column row twice) -- ensure that `desc=1` is in the url
3. Apply a filter or search
4. Resulting url/view will have `desc=True` (instead of `desc=1`)

# Cause
The jinja template renders `sort_desc` directly. Since it's a boolean, this becomes `True` in the html.

```jinja2
{# flask_admin/templates/bootstrap3/admin/model/layout.html #}
...
{% if sort_desc %}
    <input type="hidden" name="desc" value="{{ sort_desc }}">
{% endif %}
...
```

PR coming soon
