### ISSUE TITLE
# TODO: Remove me ?

### ISSUE THREAD

**Issue by OmerJog** [pallets-eco/flask-admin#1809]
What is the meaning of this function?

```
def get_pk_from_identity(obj):
    # TODO: Remove me
    key = identity_key(instance=obj)[1]
return u':'.join(text_type(x) for x in key)
```

https://github.com/flask-admin/flask-admin/blob/801a50b2c237a387a54f2d88aa4066f1a429dc47/flask_admin/contrib/sqla/fields.py#L323

**Comment by mrjoes** [comment]
Uses the SQLAlchemy `identity_key` (https://docs.sqlalchemy.org/en/latest/orm/mapping_api.html#sqlalchemy.orm.util.identity_key) to get a primary key(s) from the model and then concatenates them into a string using ':' as a separator.
