### ISSUE TITLE
[Question] How Can I Save Data In JSON file And Mix Such Model with Mongoengine ?

### ISSUE THREAD

**Issue by bekab95** [pallets-eco/flask-admin#1826]
I need to save data in JSON file and also display this data in flask-admin and mix this logic with having flask-mongoengine models too

Any Ideas ?

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
