### ISSUE TITLE
502 error with nginx with flask_mongoengine.ValidationError

### ISSUE THREAD

**Issue by Anupam02** [pallets-eco/flask-admin#1832]
I am using a `flask_mongoengine.ValidationError` for a database model, in which it is used in clean method so that it can flash a warning when save option is clicked . it's working perfectly fine when i run with standalone flask server, but its giving `nginx 502 bad gateway` when run with `flask + uwsgi + nginx`.

I am using `flask-admin` to show the model with `admin.add_view(...)` , Can someone please help to resolve this problem or if there is any other alternative I can show flash messages to the user , by validating the data on save.

`class Test(db.Document)`:
         `name = db.StringField(max_length=128, required=True, verbose_name='Name')`

    `def clean(self):
        if condition:
            msg = 'Atleast One Option has to be selected.'
            raise ValidationError(msg)

    def save(self, *args, **kwargs):
        return super(Test, self).save()`

the nginx config is 
server {
    `listen      5000;`
    `server_name localhost;`
   ` charset     utf-8;`
   ` client_max_body_size 75M;`

`location / {`
       ` include uwsgi_params;`
       ` uwsgi_pass unix:/var/www/my_app/uwsgi.sock;`
    }
}

supervisord.conf file is 
`[supervisord]`
`nodaemon=true`

`[program:nginx]`
`command=/usr/sbin/nginx`

`[program:uwsgi]`
`command =/usr/local/bin/uwsgi --ini  /etc/uwsgi/uwsgi.ini`

following is the uwsgi stack track I am getting.
`TP/1.1 200) 2 headers in 70 bytes (2 switches on core 0)`
`Traceback (most recent call last):`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)`
`File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)`
`File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()`
`File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)`
`File "/usr/local/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)`
`File "/usr/local/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)`
`File "/usr/local/lib/python2.7/site-packages/flask_admin/model/base.py", line 1888, in edit_view
    if self.update_model(form, model):`
`File "/usr/local/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 597, in update_model`
`if not self.handle_view_exception(ex):`
`File "/usr/local/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 595, in update_model`
`model.save()`
`File "./app/preset/models.py", line 146, in save
    return super(Preset, self).save()`
`File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 310, in save
    self.validate(clean=clean)`
`File "/usr/local/lib/python2.7/site-packages/mongoengine/base/document.py", line 413, in validate
    raise ValidationError(message, errors=errors)`
`mongoengine.errors.ValidationError: ValidationError (Preset:5c9895898fa63e001c8117e8) (Atleast One Adaptor Configuration is Required.: ['__all__'])`
`[pid: 9|app: 0|req: 1/3] 103.24.173.154 () {52 vars in 1590 bytes} [Mon Mar 25 10:14:39 2019] POST /preset/edit/?url=%2Fpreset%2F&id=5c9895898fa63e001c8117e8 => generated 0 bytes in 19 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)`

`False`
`[pid: 27|app: 0|req: 3/4] 178.94.48.127 () {32 vars in 465 bytes} [Mon Mar 25 10:27:10 2019] GET / => generated 2844 bytes in 42 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 0)`

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
