### ISSUE TITLE
How to use with mongoengine not flask-mongoengine ?

### ISSUE THREAD

**Issue by bekab95** [pallets-eco/flask-admin#1904]
As I see Flask-Mongoengine is dead and we need to use mongoengine directly and how ?

**Comment by amiguet** [comment]
I'm facing the same issue. Interested in using flask-admin for my mongoengine-based app, but reluctant to rely on a project that's obviously dead (flask-mongoengine). How do you guys handle this? Is there an alternative?

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
