### ISSUE TITLE
Date Picker maximum year is 2015 in editable column

### ISSUE THREAD

**Issue by quannv108** [pallets-eco/flask-admin#1909]
It just look like #1543 but I'm just using Date Field (not DateTime) in SQLite database.

<img width="738" alt="Screen Shot 2019-09-08 at 5 16 32 PM" src="https://user-images.githubusercontent.com/2249241/64486824-6b44b580-d25c-11e9-897b-f07cb6aec000.png">

Environments:
```
Flask==1.1.1
Flask-Admin==1.5.3
Flask-SQLAlchemy==2.4.0
```

**Comment by Insutanto** [comment]
I'm just used Date Field (not DateTime) in SQLite database. It is different from your picture.
![image](https://user-images.githubusercontent.com/19406290/65811413-95015480-e1ea-11e9-86e3-f7ea2d139fbd.png)

Environments:
Flask==1.1.1
flask_admin==1.5.3
flask_sqlalchemy==2.4.1
SQLAlchemy==1.3.8

**Comment by samuelhwilliams** [comment]
I believe this issue is fixed in the bootstrap4 theme/template_mode.

If you're still using bootstrap2 or bootstrap3, please upgrade :)

If the issue persists, please raise a new ticket. Thanks.
