### ISSUE TITLE
Geoalchemy example not working?

### ISSUE THREAD

**Issue by swaxolez** [pallets-eco/flask-admin#1910]
I'm trying to decide if I can use flask-admin with geoalchemy.  I'm a complete novice to flask.  It looks like MAPBOX_MAP_ID is deprecated with Mapbox?

**Comment by gmoscovitch** [comment]
I am also trying to run this but it seems this url:
https://api.mapbox.com/styles/v1/mapbox/'+window.MAPBOX_MAP_ID+'/tiles/{z}/{x}/{y}?access_token='+window.MAPBOX_ACCESS_TOKEN
is not valid anymore

**Comment by ishiland** [comment]
Did you try something like `MAPBOX_MAP_ID = 'light-v10'`? There may be some css issue but I can get  the tiles to display this way.

**Comment by samuelhwilliams** [comment]
I've added `MAPBOX_MAP_ID = 'light-v10'` to the example directly - should make it a bit easier to run.
