### ISSUE TITLE
Translations not extracted

### ISSUE THREAD

**Issue by lnlrbr** [pallets-eco/flask-admin#1974]
Some sentences are not extracted in .PO files, like "Delete record". Seems to re-run a pybabel extract

**Comment by forlAIght** [comment]
Does this mean that  some fields are translated , some are not?(Most of them is the defaulted template, like "list" "edit" "create")
I am also troubled by this problem.   （Mark!

**Comment by LionelR** [comment]
Yes. The majority of the sentences are translated but some aren't.
