### ISSUE TITLE
Consulting/Development Services

### ISSUE THREAD

**Issue by acedrew** [pallets-eco/flask-admin#2081]
I'm using flask admin in a new management portal, perhaps ill-advisedly, given the low activity on the project in the last 12 months. I'm filing an issue to see if there are members of the community that might consider sponsorship or direct contracting to improve certain pieces of the project that are road blockers for my use case, as well as get some of the backlog of pull requests QA'd and pushed through.

Thanks,
Andrew Rodgers
ACE IoT Solutions

**Comment by davidism** [comment]
Flask-Admin is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on the `#pallets-eco` channel on [the Pallets Discord server](https://discord.gg/pallets).
