### ISSUE TITLE
How to pass parameters from flask to the index page?

### ISSUE THREAD

**Issue by zerefiks** [pallets-eco/flask-admin#2147]
I have an index page template for the home page:
'template/admin/index.html'
How to pass a parameter there `test='test_param'` from a flask?

**Comment by caffeinatedMike** [comment]
Subclass the [`AdminIndexView`](https://flask-admin.readthedocs.io/en/latest/api/mod_base/#default-view) and check `request.args` like you would with any other Flask route. But, remember to register the custom index view when instantiating the `Admin` class.
