### ISSUE TITLE
Easy way to override mongoengine inline form template

### ISSUE THREAD

**Issue by zloyded** [pallets-eco/flask-admin#2218]
i cant find some way to override inline_form templates for Embedded forms (Mongoengine)
([this](https://github.com/flask-admin/flask-admin/blob/2f6d8f00349f0fce4b5745f9f09e7562228b1ba1/flask_admin/model/widgets.py#L12) and [this](https://github.com/flask-admin/flask-admin/blob/2f6d8f00349f0fce4b5745f9f09e7562228b1ba1/flask_admin/model/widgets.py#L17) )
Have some best way to override it?

**Comment by zloyded** [comment]
May be possible add parameter to ModelView class like `create_modal_template`, just for `inline_list_base` template?
Just, not so good have form with `"New Пользователи"` or with other languages. 
Templates -- hardcoded.
Template form -- hardcoded.

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
