### ISSUE TITLE
Migrate `S3FileAdmin` from `boto` to `boto3`

### ISSUE THREAD

**Issue by tgross35** [pallets-eco/flask-admin#2278]
Boto is no longer maintained, and has been replaced by `boto3`. This is described on the two project pages: https://github.com/boto/boto and https://github.com/boto/boto3. However, flask-admin still relies on the older `boto`:

`Could not import boto. You can install boto by using pip install boto`

The migration is fairly straightforward

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/migration.html

**Comment by samuelhwilliams** [comment]
[We'll track this on another issue](https://github.com/pallets-eco/flask-admin/issues/2347)
