### ISSUE TITLE
S3FileAdmin runs on (old) boto. 

### ISSUE THREAD

**Issue by israel-oye** [pallets-eco/flask-admin#2347]
https://github.com/flask-admin/flask-admin/blob/46d5a6ee5dd4d298c8824047a4cd9f7cc404348a/flask_admin/contrib/fileadmin/s3.py#L4

`boto` is no more maintained and it has been replaced by the latest [boto3](https://github.com/boto/boto3#boto3---the-aws-sdk-for-python) library. 
I'm surprised that this issue has not been raised earlier but I guess not many people use the `S3FileAdmin` layer for their Flask-Admin. I would be happy to contribute to updating the `S3FileAdmin` add-on but I need to get a hang of it's documentation.
Added to my to-do!
I'm sure @metadaddy will be willing to help.

**Comment by samuelhwilliams** [comment]
Would be happy to accept a pull request for this :)
