### ISSUE TITLE
Auth Example is out of date

### ISSUE THREAD

**Issue by jlebrech** [pallets-eco/flask-admin#2370]
this example `https://github.com/flask-admin/Flask-Admin/tree/master/examples/auth` is causing the following error.

`AttributeError: 'Flask' object has no attribute 'before_first_request'`

`before_first_request` was deprecate in 2.3.0 but is somehow still being used by flask-security

https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0

**Comment by Dosenpfand** [comment]
Can be resolved by switching from `Flask-Security` to `Flask-Security-Too` as described in #2373 .
