### ISSUE TITLE
Flask-admin with React

### ISSUE THREAD

**Issue by webbythien** [pallets-eco/flask-admin#2379]
How can I combine jar-admin with React, for example can I replace template with React instead of basic html, please help me.

**Comment by Zasgard** [comment]
By jar-admin, I'm guessing thats a typo and you meant to type Flask-admin right? Assuming that's the case, I would recommend using flask admin to render the static html. Within the static components, you can include react components that will dynamically call the server using ajax for dynamic usage. That way you have the server side content sent through the jinja template and the react components dynamically rendering things on the client side.

**Comment by samuelhwilliams** [comment]
This issue is quite old now, and I think it's probably no longer relevant (or you've since worked out what to do). I'm going to close this issue, but if you disagree, please feel free to reply again or open a new issue.
