### ISSUE TITLE
not compatible with `WTForms-3.1.0` and `Babel-2.13.0`

### ISSUE THREAD

**Issue by mattibo** [pallets-eco/flask-admin#2391]
i just updated two depending libraries:
* `WTForms` to latest version `3.1.0`
* `Babel` to the latest versino `2.13.0`

After this the internationalization is not working and i cannot create entities because of following error:

![image](https://github.com/flask-admin/flask-admin/assets/3369294/498c687f-c76f-4663-b6de-9bc4e5eaa74c)

**Comment by vastroh** [comment]
ValueError: not enough values to unpack (expected 4, got 3)

Probably related to this change https://github.com/wtforms/wtforms/pull/739

**Comment by guidoiaquinti** [comment]
Related: https://github.com/wtforms/wtforms/issues/814#issuecomment-1775455093 and https://github.com/wtforms/wtforms/issues/811

**Comment by aminalaee** [comment]
Just for ref, this will add backwards compatiblity to wtforms: https://github.com/wtforms/wtforms/pull/816

**Comment by samuelhwilliams** [comment]
Thanks for sharing the extra info, including example patch. I'm currently working on getting the project into a standardised structure (for pallets-eco projects); after that I'd be happy to help get this in. Feel free to raise a PR and I'll help review it.

**Comment by samuelhwilliams** [comment]
WTForms restored compatibility for 3-item tuples in v3.1.1, so my gut feeling is that maybe we don't need to do anything in flask-admin now.
