### ISSUE TITLE
Multiple selection from dropdown list.

### ISSUE THREAD

**Issue by Dolgopolovww** [pallets-eco/flask-admin#2403]
I'm trying to implement multiple selection from a list. There are 2 tables: users and categories; one user can have several categories. In the database, tables are related m2m.
But when I go to the admin panel, I cannot select multiple values, I can only select one. How to solve this problem??

**Comment by Acrofil** [comment]
Hi.

Take a look at Select2Field

` 'widget': Select2Field(multiple=True) ` should achieve what you want
