### ISSUE TITLE
 aioflask with Flask>=3.0

### ISSUE THREAD

**Issue by wathika-eng** [pallets-eco/flask-admin#2418]
from flask import _request_ctx_stack
ImportError: cannot import name '_request_ctx_stack' from 'flask'

Tried fixing with https://github.com/miguelgrinberg/aioflask/issues/10

**Comment by samuelhwilliams** [comment]
Is this an issue in Flask-Admin directly, or some other package?

**Comment by samuelhwilliams** [comment]
Closing as a duplicate of https://github.com/pallets-eco/flask-admin/issues/2413. I think there's probably some overlap here, but if you mean something slightly different please do open another issue with some additional information.
