### ISSUE TITLE
Seeking help from additional volunteers?

### ISSUE THREAD

**Issue by macnewbold** [pallets-eco/flask-admin#2421]
It seems like the current maintainer team doesn't have a lot of time available for the project currently. There are a lot of people (myself included) who still use it regularly and would love to help ensure that it keeps evolving, and getting fixes and improvements merged and released.

Is the project currently looking for additional help with maintenance and releases?

**Comment by Soham7777777** [comment]
Hi! I am a university student, and I love this project and want to improve the project, While also maintaining the flexibility of this project. The problem is that I don't know where to start, what to start fixing, and sometimes also how to fix it. I am ready to volunteer for this project.

**Comment by hasansezertasan** [comment]
Count me in.

**Comment by macnewbold** [comment]
Mostly I'm looking at the latest release (June 2023, currently over 9 months ago) and the number of things merged since then (at least 27 merges if I counted right), and the number of pending pull requests (75 open as I write this). I know personally I've been waiting for over 6 months for a few bugfixes to be in "the next release" but it hasn't happened yet. My guess/assumption was that the wonderful volunteers who maintain the project are short on time to dedicate to this, and wondered if more hands might lighten their load. Not every project welcomes it readily, as there can be risks or complications to broadening the group of committers or maintainers, but I thought it was worth asking. I'm excited to see others are interested in helping too!

**Comment by TheoLechemia** [comment]
Hi, 
I'm interessed in helping in the project too as we use a lot Flask-Admin in our organization

**Comment by samuelhwilliams** [comment]
I'd also be happy to volunteer some time to help maintain this, either sorting through issues or adding small fixes/features (or both).

**Comment by davidism** [comment]
Flask-Admin is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on the `#pallets-eco` channel on [the Pallets Discord server](https://discord.gg/pallets).

@macnewbold @hasansezertasan @TheoLechemia

**Comment by hasansezertasan** [comment]
> Flask-Admin is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on the `#pallets-eco` channel on [the Pallets Discord server](https://discord.gg/pallets).

Great news, thank you @davidism for your response. I just joined the server 😉.
