### ISSUE TITLE
Can't use multiple `Admin` instances with different Bootstrap themes (`FLASK_ADMIN_SWATCH`)

### ISSUE THREAD

**Issue by princerb** [pallets-eco/flask-admin#2423]
❓  How can we use different Bootstrap themes through multiple `Admin` instances?

👨‍💻  This is how I tried to do it:
```python
...
app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
admin1 = Admin(app, endpoint='admin1')
app.config['FLASK_ADMIN_SWATCH'] = 'cosmo'
admin2 = Admin(app, endpoint='admin2')
...
```
❌  But this does NOT work, I wrote this to clarify what I want to do with my issue.
_Thanks!_

**Comment by princerb** [comment]
If I solve, will PRs be viewed/merged soon?

**Comment by samuelhwilliams** [comment]
This feels like a useful feature. I'm not sure yet how easy or hard it would be to support this, but if you've got ideas I'd be happy to hear them and would be willing to help review any PR you do put up. Would be good to understand your proposed approach first.

**Comment by samuelhwilliams** [comment]
I had a look at this and it might be something we could get into the v2 release. Here's a possible approach: https://github.com/pallets-eco/flask-admin/pull/2462

As I've coded it, it's a breaking change. We could make this a bit softer and wrap the breaking change if we really wanted to - although since we're planning a v2.0.0 release, now's a fair time to get it in.

**Comment by princerb** [comment]
I actually already made the reslover changes for this, just needed to write the end of the example ) [the button that switches even the current theme]

**Comment by princerb** [comment]
@samuelhwilliams as I see you created a complete new configuration class for the Bootstrap options, while I used a new param to `Admin` which is `bootswatch_theme`. I think your approach also is awesome 👍

**Comment by samuelhwilliams** [comment]
I'd love to see what you've done so far or what you're planning - if you've covered some use cases that I haven't, we can take the best of both :)

**Comment by princerb** [comment]
#2463

**Comment by princerb** [comment]
But mine is quite simple one. Your approach gives the project a seperate and full control over the theming. But there is a catch, you added also `folder` param, are we also going to plan to use different Bootstrap versions along along the different `Admin` instances?

**Comment by samuelhwilliams** [comment]
> But there is a catch, you added also folder param, are we also going to plan to use different Bootstrap versions along along the different Admin instances?

I don't think we *need* to. We might not even have to. But with my approach it becomes trivial to make it _possible_ - and I think the more interesting idea is where someone has multiple admin instances for different groups of users. These could be user-provided template configs that point at their own private set of templates configured for each user group specifically. It feels fairly flexible without really costing us much.

**Comment by princerb** [comment]
I thought about this when I am making changes, but there were going to be more core changed needed to be done. I haven't really structured this feature in my head, but I think it requires the changes through the Boostrap template folders and some alternations when creating and registering the `Blueprint` from the base.

**Comment by princerb** [comment]
> > But there is a catch, you added also folder param, are we also going to plan to use different Bootstrap versions along along the different Admin instances?
> 
> I don't think we _need_ to. We might not even have to. But with my approach it becomes trivial to make it _possible_ - and I think the more interesting idea is where someone has multiple admin instances for different groups of users. These could be user-provided template configs that point at their own private set of templates configured for each user group specifically. It feels fairly flexible without really costing us much. Each admin instance can we styled exactly the way it wants/needs to be.

My guess is that when the users use multiple `Admin` instances, they might also want to use also different Bootstrap versions if need. But your reply sounds fair 👍
