### ISSUE TITLE
Flask Admin Reboot: A community version to submit changes

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pallets-eco/flask-admin#2427]
Hi all, i have been tinkering around Flask admin with a fork. If you want to submit changes, get them merged to use in a project, feel free to PR to this one: https://github.com/Abdur-rahmaanJ/flask-admin-reboot, available on pypi as flask-admin-reboot.

**Comment by Abdur-rahmaanJ** [comment]
If you have enough experience and want to admin, volunteer on the repo ^^

**Comment by hasansezertasan** [comment]
> If you have enough experience and want to admin, volunteer on the repo ^^

What do you mean by "volunteer on the repo"?

**Comment by Abdur-rahmaanJ** [comment]
@hasansezertasan Just open an issue saying i want to help maintain.

**Comment by hasansezertasan** [comment]
> @hasansezertasan Just open an issue saying i want to help maintain.

Issues are not activated at your fork.

**Comment by Abdur-rahmaanJ** [comment]
Closing, now the project is in Pallets-eco
