### ISSUE TITLE
Remove Flask-BabelEx support?

### ISSUE THREAD

**Issue by samuelhwilliams** [pallets-eco/flask-admin#2447]
[Flask-BabelEx](https://github.com/mrjoes/flask-babelex) has been archived and marked as deprecated by the owner, with [Flask-Babel](https://github.com/python-babel/flask-babel) back on the table.

Maybe we should drop all of the code that supports Flask-BabelEx and move back to supporting just Flask-Babel. There have been a few PRs around this topic which I've closed for being old - will track conversation on this here instead.

**Comment by Abdur-rahmaanJ** [comment]
Good move! @aenglander this is a good milestone candidate!

**Comment by mrjoes** [comment]
Flask-Babel merged all Flask-BabelEx changes and it’s now possible to fully
migrate to Flask-Babel.
