### ISSUE TITLE
Remove (flask-)mongoengine support?

### ISSUE THREAD

**Issue by samuelhwilliams** [pallets-eco/flask-admin#2466]
[`flask-mongoengine`](https://github.com/MongoEngine/flask-mongoengine) appears to be dead, and isn't compatible with Flask>=2.3.0.

Should we stop supporting it? What're the alternatives? Is `pymongo` enough?

**Comment by princerb** [comment]
**The dead frameworks should be removed. But I guess `flask-mongoengine` which uses `MongoEngine `is high-level abstraction and implemented with a lot of features. If we only stay with `PyMongo`, it is perfect itself. How about we remove it in the next release?**

Until then, currently, we add a warning message to all `MongoEngine` users to tell them that *we are dropping support for FLask-MongoEngine usage from x.x.x version, and please migrate to mongo or stay with the old version of flask-admin*?

But I also want to hear others' opinions about this)

**Comment by samuelhwilliams** [comment]
I've gone back and forth on this a little bit.

Given `flask-mongoengine` appears to be unsupported/unmaintained, is incompatible with newer versions of our core dependencies (eg flask/wtforms), and has no obvious popular replacement (there are a couple, but much smaller community presence), I propose that we remove `flask-mongoengine` support from Flask-Admin in v2.0.0 onwards.

If `flask-mongoengine` becomes maintained again, or a fork picks up a clear broad base of support and is brought up-to-date, then I'd be glad and keen to add support back in.
