### ISSUE TITLE
Filter 'Apply' Button Visibility Issue Introduced in PR #2501

### ISSUE THREAD

**Issue by pajusmar** [pallets-eco/flask-admin#2520]
After the merge of #2501, the [filter "Apply" button](https://github.com/pallets-eco/flask-admin/blob/5d07c88eb953ebc801106b184bc8de4f3726919a/flask_admin/templates/bootstrap4/admin/model/layout.html#L49) is visible even when no filter option has been selected. This button should only appear when a filter option is selected. Multiple class attributes were applied to the button element. Previously, `style="display: none;"` was used to toggle the visibility.

### Steps to Reproduce

1. Go to a page where the filtering is enabled.
2. The "Apply" button is visible despite no filters being selected.

### Expected Behavior
The "Apply" button should be hidden when no filters are selected and only appear when a filter option is selected.

### Possible Solution
The issue might be resolved by revising the Javascript code from bs4_filters.js.

Environment:

- Python version: 3.10
- Flask version: 3.0.3
- Flask-Admin version: 2.0.0a0

**Comment by samuelhwilliams** [comment]
Thanks for spotting this. Should be fixed by #2524 🙏

**Comment by pajusmar** [comment]
I came across this while improving Estonian translations and updating the Babel application in the example folder to display more translations in the user interface. The pull request for the translations seems to be bigger than I initially anticipated. Additionally, I found untranslated text, which I should include in a separate pull request to make it easier to review.
