### ISSUE TITLE
Update to `wtforms` 3.2 breaks with flask admin from `SelectFieldBase` import

### ISSUE THREAD

**Issue by om-henners** [pallets-eco/flask-admin#2544]
Updating [wtforms](https://github.com/pallets-eco/wtforms) 3.1.2 to the new release [3.2](https://github.com/pallets-eco/wtforms/releases/tag/3.2.0) causes flask-admin to raise an import error:

```
    from flask_admin.contrib.sqla.ajax import QueryAjaxModelLoader
/usr/opt/venv/lib/python3.11/site-packages/flask_admin/contrib/sqla/__init__.py:2: in <module>
    from .view import ModelView
/usr/opt/venv/lib/python3.11/site-packages/flask_admin/contrib/sqla/view.py:24: in <module>
    from flask_admin.contrib.sqla import form, filters as sqla_filters, tools
/usr/opt/venv/lib/python3.11/site-packages/flask_admin/contrib/sqla/form.py:11: in <module>
    from flask_admin.model.fields import AjaxSelectField, AjaxSelectMultipleField

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    import itertools

    from wtforms.validators import ValidationError
>   from wtforms.fields import FieldList, FormField, SelectFieldBase
E   ImportError: cannot import name 'SelectFieldBase' from 'wtforms.fields' (/usr/opt/venv/lib/python3.11/site-packages/wtforms/fields/__init__.py)

/usr/opt/venv/lib/python3.11/site-packages/flask_admin/model/fields.py:4: ImportError
```

This appears to be related to the change here: https://github.com/pallets-eco/wtforms/commit/f6cc1f5192263c64d06fededd2e06ed654eabb1e (`SelectFieldBase` is no longer in the `fields` submodule without the `import *`).

Ideally this should be updated to import specifically from `wtforms.fields.choices`

Environment:

- Python version: 3.11 (same with 3.12)
- Flask version: 3.0.3
- Flask-Admin version: 1.6.1

**Comment by miettal** [comment]
it seems this error was fixed in wtforms==3.2.1

https://github.com/pallets-eco/wtforms/releases/tag/3.2.1

**Comment by om-henners** [comment]
Thanks - I'll give it a try now and see how it goes.

**Comment by om-henners** [comment]
Yeah, unfortunately upgrading to 3.2.1 breaks flask-admin in a number of other ways as well. It's not the same issue, so I'll close this and open new issues for the issues I've found.
