### ISSUE TITLE
Make bootstrap3 default template_mode?

### ISSUE THREAD

**Issue by gstf** [pallets-eco/flask-admin#822]
Maybe it's time to deprecate Bootstrap 2 support? Bootstrap 4 will probably soon be here. A good start is to make bootstrap3 the default for template_mode.

**Comment by ibushong** [comment]
FWIW I think the current Bootstrap 3 implementation needs work. A few examples:

1) The choice of icons for displaying booleans is poor IMO, as both options (true, false) look very similar. Makes looking over large lists with booleans difficult (compared to the previous implementation of a checkmark for true and blank for false). 
2) The form validation templating needs some fixes. For example, for field validation errors, the fields/messages are not highlighted in red, making it difficult to see what fields are wrong (this is implemented correctly in bootstrap 2)

**Comment by pawl** [comment]
@ibushong 

1) Looks like this is working properly?
Bootstrap 2: http://i.imgur.com/08YYAY9.png
Bootstrap 3: http://i.imgur.com/aIDjnwn.png

2) The icons look pretty similar between Bootstrap 2/3, which ones do you think would be better?
* Bootstrap 2: http://i.imgur.com/mtSBmlc.png
* Bootstrap 3: http://i.imgur.com/eIXyUSH.png

I think setting bootstrap3 as default sounds like a good idea. It's not very difficult for developers who upgrade flask-admin to set template_mode="bootstrap2" if they want to continue using bootstrap2.

**Comment by ibushong** [comment]
@pawl 

1) Looks like this has been fixed or maybe I had a bug in my implementation before. 

2) Sorry I guess it's not related only to bootstrap3, but rather to flask_admin updates overall, to support bootstrap3. Here's the difference I'm referring to:

- Before: http://i.imgur.com/RrtrTC1.png
- Current: http://i.imgur.com/Jjq4n4X.png

The "before" version is much clearer to me, especially when I have huge tables with boolean values. In the "current" version, at a glance, it looks like all values are True. Having the empty space for False is much more readable to me. 

[Here's](https://github.com/mrjoes/flask-admin/commit/d2dc70741066dd7ee5489bf7e51ca04923b54845) the relevant commit.
