### ISSUE TITLE
Cannot create separate instances of Admin with different template mode

### ISSUE THREAD

**Issue by plaes** [pallets-eco/flask-admin#895]
Setting different template modes does not work with multiple instances like one would expect:

```
    admin1 = admin.Admin(app, url='/admin1')
    admin1.add_view(FirstView())

    # Create second administrative interface under /admin2
    admin2 = admin.Admin(app, url='/admin2', endpoint='admin2', template_mode='bootstrap3')
    admin2.add_view(SecondView())
```

The outcome is that, `admin2` is still using bootstrap2.

**Comment by petrus-jvrensburg** [comment]
I don't think this is a bug. The default value is `bootstrap2`, so if it's not explicitly set for admin1, then that is what I would expect.

**Comment by plaes** [comment]
@petrus-jvrensburg I'm having issue with `admin2`, not `admin1`.

**Comment by petrus-jvrensburg** [comment]
Aah, I see. I misread. 

Any chance that you can fix this and make a PR?

**Comment by samuelhwilliams** [comment]
This will be (technically) available in the [next planned release](https://github.com/pallets-eco/flask-admin/issues/2451), although we are removing the old bs2 and bs3 themes, leaving only a bs4 theme.

However, if you bring your own themes, you will be able to have multiple admin instances with different themes applied.

**Comment by princerb** [comment]
Related to #2423
