### ISSUE TITLE
CRUD on GenericEmbeddedDocumentField in mongoengine 

### ISSUE THREAD

**Issue by spitzbubchen** [pallets-eco/flask-admin#905]
It seems that it is not possible to perform CRUD on embedded documents in a GenericEmbeddedDocumentField with the choices option? For example:

```
class Test1(db.EmbeddedDocument):
    label = db.StringField(max_length = 32)

class Test2(db.EmbeddedDocument):
    label = db.StringField(max_length = 32) 

class Tasks(db.Document):
    structure1 = db.ListField(db.EmbeddedDocumentField(Test1))
    structure2 = db.ListField(db.GenericEmbeddedDocumentField(choices = (Test1, Test2)))

    def __unicode__(self):
        return unicode(self.name)
```

For structure2 I want to select either Test1 or Test2 and then edit the embedded document, however, I am only given a list. On the other hand structure1 work well.

**Comment by pawl** [comment]
I think there's already one open for this: https://github.com/flask-admin/flask-admin/issues/741

**Comment by spitzbubchen** [comment]
Yes, it seems the same, however, I get no errors, just a select box with no option to perform CRUD on the choices. Should I leave this open or close it?

**Comment by mrjoes** [comment]
Straightforward way would be to extend the form converter and add custom field (and widget) that knows how to generate forms for embedded models, show drop-down with a choice and dynamically switch between forms.

Right now, most of the form scaffolding work is done by the flask.ext.mongoengine though.

**Comment by samuelhwilliams** [comment]
I am closing this issue as we've removed support for flask-mongoengine, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
