### ISSUE TITLE
mongoengine allow_inheritance for an embedded document

### ISSUE THREAD

**Issue by spitzbubchen** [pallets-eco/flask-admin#907]
For flask-admin the following only gives me CRUD access to Task and the TaskItem embedded document, but no access to ItemParameter or ItemTitle. Is this not supported in flask-admin or am I doing something wrong? Thx

```
class TaskItem(db.EmbeddedDocument):
    type = db.StringField(max_length = 32)
    column = db.IntField()
    row = db.IntField()
    width = db.IntField()
    height = db.IntField()
    meta = {'allow_inheritance': True}


class ItemParameter(TaskItem):
    label = db.StringField(max_length = 32)
    formula = db.StringField(max_length = 256)
    parameter = db.ReferenceField(Parameter)


class ItemTitle(TaskItem):
    label = db.StringField(max_length = 32)
    document = db.ReferenceField(Document)


class Task(db.Document):
    items = db.ListField(db.EmbeddedDocumentField(TaskItem))

    def __unicode__(self):
        return unicode(self.name)


# Flask-Admin
class SecuredModelView(ModelView):
    def is_accessible(self):
        return current_user.has_role('admin')


admin.add_view(SecuredModelView(Task))
```

**Comment by mrjoes** [comment]
Not sure how Flask-Admin would handle this one. The framework generates only one form per model. You have polymorphic (or inherited) models that have different fields and Flask-Admin would show that one base form, without extra fields.

Also, it is hard to Flask-Admin to know what kind of model it is without keeping mapping between classes and form types. I guess it is possible to return correct form from `get_form` method, but have no idea how to handle model creation, as you should have ability to create three different models from one page.

**Comment by Fraggle** [comment]
Maybe we coud use the choices=.... to list the various authorized subclass, generate X subform (one per subclass) and let the user pick thru a button with one he wants to use.
What do you think about that?

**Comment by ufo911** [comment]
Such needed feature no works ?

**Comment by ufo911** [comment]
I agree with @Fraggle nice Idea

**Comment by samuelhwilliams** [comment]
I am closing this issue as we're removing support for flask-mongoengine in the next release, because that library is no longer being maintained and is incompatible with recent versions of our core dependencies (eg flask, wtforms, etc).
